#!/usr/bin/env bash
#
# open  /media/me
# close /media/me [me] loop20 tomb.me.1523798393.loop20

case "$1" in
    open)
        electrum daemon start
        electrum daemon load_wallet
        ;;
    close)
        electrum daemon close_wallet
        electrum daemon stop
        ;;
esac

electrum daemon status

exit 0
