#!/usr/bin/env bash

lock () {
    local file="$1"
    local content="$2"

    set -o noclobber

        { > "${file}"; } &> /dev/null; local status=$?

    set +o noclobber

    [ ${status} -eq 0 ] && {
        echo "${content}" > "${file}" && return 0 || rm -f "${file}"
    }

    return 1
}
